extends "res://tests/player_stage6_test.gd"
## Source-visible light beams hit exact mirrored enemies in the next role only.

func emitter(index: int) -> Node3D:
	return panels[index].arena.get_node("LightBeams")

func run_checks() -> void:
	await fresh_page()
	var target: CharacterBody3D = panels[1].arena.enemies.get_child(0)
	target.position = Vector3(8, 0.8, 0)
	await ticks(2)
	await key(KEY_E)
	check(emitter(0).shots_fired == 1 and emitter(0).bolts.get_child_count() == 1 and emitter(1).bolts.get_child_count() == 0, "E creates a visible beam in the current Past panel, aimed at Present mirages")
	check(not emitter(0).fire(), "Beam cooldown prevents rapid spam")
	await ticks(15)
	check(target.health == 4 and target.hit_count == 1, "Beam hitting the visible mirage damages the corresponding Present enemy exactly once")
	check(emitter(0).impact_count == 1 and emitter(0).impact.position == target.position, "Hit feedback appears at the struck mirage in the current panel")
	check(page.health == 6 and panels[0].arena.enemies.get_child(0).health == 6 and panels[2].arena.enemies.get_child(0).health == 6, "Mirage hits cannot damage local enemies, unrelated panels, or players")
	await ticks(20)
	check(target.hit_count == 1, "Piercing beam never repeatedly damages one target")
	await fresh_page()
	page.select_panel(1)
	target = panels[2].arena.enemies.get_child(0)
	target.position = Vector3(8, 0.8, 0)
	await ticks(2)
	check(emitter(1).fire() and emitter(1).last_destination == 2, "Present fires at Future mirages")
	await ticks(15)
	check(target.health == 4 and emitter(1).impact_count == 1, "Visible Present beam hits its corresponding Future enemy")
	page.select_panel(2)
	check(not emitter(2).fire() and emitter(2).cooldown_left == 0.0, "Future has no forward beam targets")
	check(not InputMap.has_action("far_beam"), "Confusing direct-Past-to-Future input is removed")

	await fresh_page()
	page.twist_timeline()
	page.select_panel(2)
	check(emitter(2).fire() and emitter(2).last_destination == 0, "Shots follow roles rather than numeric panel identities")
	page.set_paused(true)
	page.twist_timeline(true)
	await ticks(2)
	check(emitter(2).bolts.get_child_count() == 0, "Role changes cancel a beam whose target no longer matches its displayed mirages")
	page.set_paused(false)

	for wall_index in [0, 1]:
		await fresh_page()
		target = panels[1].arena.enemies.get_child(0)
		target.position = Vector3(8, 0.8, 0)
		var wall := StaticBody3D.new()
		var collision := CollisionShape3D.new()
		var shape := BoxShape3D.new()
		shape.size = Vector3(0.2, 3, 2)
		collision.shape = shape
		wall.add_child(collision)
		wall.position = Vector3(6.8, 1, 0)
		panels[wall_index].arena.add_child(wall)
		await ticks(2)
		emitter(0).fire()
		await ticks(20)
		check(target.health == 6 and emitter(0).bolts.get_child_count() == 0, "Wall in arena %d blocks the visible beam and remote damage" % (wall_index + 1))

	await fresh_page(true, true)
	emitter(0).fire()
	var bolt: Node3D = emitter(0).bolts.get_child(0)
	var start: float = bolt.position.x
	await ticks(6)
	check(absf(bolt.position.x - start - 2.04) < 0.02, "Visible Past beam follows the firing arena's 85% clock")
	page.select_panel(1)
	start = bolt.position.x
	await ticks(6)
	check(absf(bolt.position.x - start - 0.24) < 0.02, "Switching away slows the source beam with its arena")
	page.set_paused(true)
	start = bolt.position.x
	var cooldown: float = emitter(0).cooldown_left
	await ticks(20)
	check(bolt.position.x == start and emitter(0).cooldown_left == cooldown and not emitter(1).fire(), "Pause freezes visible beams and cooldowns")
	Input.action_press("light_beam")
	page.set_paused(false)
	await ticks(2)
	check(emitter(1).shots_fired == 0, "Menu-time held beam cannot fire on resume")
	Input.action_release("light_beam")
	await ticks(2)
	await tap("light_beam")
	check(emitter(1).shots_fired == 1, "Fresh beam input works after resume")

	await fresh_page()
	Input.action_press("light_beam")
	await ticks(1)
	page.select_panel(1)
	await ticks(70)
	check(emitter(1).shots_fired == 0, "Held input never fires in the newly selected panel")
	Input.action_release("light_beam")
	await ticks(2)
	await tap("light_beam")
	await ticks(100)
	check(emitter(1).shots_fired == 1, "Holding or waiting does not repeat shots")

	await fresh_page()
	panels[0].arena.player.position = Vector3(16, 4, 0)
	panels[0].arena.player.facing_direction = -1
	target = panels[1].arena.enemies.get_child(0)
	target.position = Vector3(14, 4, 0)
	target.set_physics_process(false)
	check(emitter(0).fire(), "Airborne left-facing beam launches")
	await ticks(10)
	check(target.health == 4 and emitter(0).impact_count == 1, "Airborne mirage can be hit from the matching source height")
	await ticks(100)
	check(emitter(0).bolts.get_child_count() == 0, "Beams expire or stop at walls without leaking")

	await fresh_page()
	target = panels[1].arena.enemies.get_child(0)
	target.position = Vector3(7, 0.8, 0)
	await ticks(2)
	emitter(0).fire()
	bolt = emitter(0).bolts.get_child(0)
	bolt.set_physics_process(false)
	bolt._physics_process(0.2)
	check(target.health == 4, "Swept cross-world hit detects a target between projectile endpoints")
	await fresh_page()
	for i in range(emitter(0).MAX_BEAMS):
		emitter(0).cooldown_left = 0.0
		emitter(0).fire()
	emitter(0).cooldown_left = 0.0
	check(not emitter(0).fire() and emitter(0).bolts.get_child_count() == emitter(0).MAX_BEAMS, "Visible projectile pool is bounded per firing arena")
	panels[0].arena.player.receive_damage(100)
	await ticks(2)
	check(emitter(0).bolts.get_child_count() == 0 and not emitter(0).fire(), "Defeat clears beams and disables firing")
	await key(KEY_R)
	await ticks(80)
	page = current_scene
	panels = page.panels
	check(emitter(0).shots_fired == 0 and emitter(0).cooldown_left == 0.0 and emitter(0).bolts.get_child_count() == 0, "Restart clears all beam state")
	check(is_equal_approx(Engine.time_scale, 1.0), "Mirage combat never changes global time")
	print("STAGE 9 MIRAGE BEAM CHECKS COMPLETE: ", failures, " failures")
	quit(1 if failures else 0)
