extends "res://tests/causal_test_base.gd"
var sfx: Node

func reset_cues() -> void:
	sfx.last_played.clear()
	sfx.history.clear()
	sfx.played_counts.clear()

func heard(cue: StringName) -> bool:
	return sfx.history.has(cue)

func run_checks() -> void:
	await fresh()
	sfx = root.get_node("Sfx")
	check(sfx.voices.size() == 24 and sfx.streams.size() == sfx.CUES.size(), "Every cue has a cached stream and audio uses a fixed 24-voice pool")
	for cue: StringName in sfx.CUES:
		var stream: AudioStream = sfx.streams[cue]
		check(stream != null and stream.get_length() > 0.02 and stream.get_length() <= 8.0, "Short usable audio loads for " + String(cue))
	var fighter: CharacterBody3D = page.panels[0].arena.player
	await ticks(20)
	reset_cues()
	key(KEY_D, true)
	await ticks(30)
	key(KEY_D, false)
	check(heard(&"footstep"), "Actual grounded player movement emits distance-timed footsteps")
	reset_cues()
	key(KEY_SPACE, true)
	await ticks(1)
	key(KEY_SPACE, false)
	await ticks(4)
	check(heard(&"jump"), "Accepted ground jump triggers its takeoff cue")
	key(KEY_SPACE, true)
	await ticks(1)
	key(KEY_SPACE, false)
	await ticks(2)
	check(heard(&"double_jump"), "Accepted airborne jump triggers a distinct cue")
	reset_cues()
	key(KEY_SHIFT, true)
	await ticks(1)
	key(KEY_SHIFT, false)
	await ticks(2)
	check(heard(&"dash"), "Accepted air dash emits its cue")
	var dash_count: int = sfx.played_counts.get(&"dash", 0)
	await ticks(25)
	key(KEY_SHIFT, true)
	await ticks(1)
	key(KEY_SHIFT, false)
	await ticks(2)
	check(sfx.played_counts.get(&"dash", 0) == dash_count, "Rejected second air dash produces no fake dash cue")
	await ticks(80)
	check(heard(&"landing"), "Real touchdown triggers a landing cue")
	reset_cues()
	key(KEY_J, true)
	await ticks(1)
	key(KEY_J, false)
	await ticks(8)
	check(heard(&"swing"), "Swing cue starts when the attack enters its live window")
	reset_cues()
	key(KEY_F, true)
	await ticks(1)
	key(KEY_F, false)
	await ticks(2)
	check(heard(&"parry_start"), "Accepted parry emits a guard cue")
	var id: int = populate()
	var victim: CharacterBody3D = page.ledger.actor_for(id, 0)
	victim.position = fighter.position + Vector3(fighter.facing_direction, 0, 0)
	fighter.parry.window_left = 0.2
	check(fighter.parry.try_parry(victim) and heard(&"parry_success"), "Successful facing parry emits a distinct impact cue")
	reset_cues()
	page.addition = 4
	victim.receive_melee_hit(100, 1)
	check(heard(&"hit") and heard(&"enemy_death") and heard(&"add_ready") and page.addition == 5, "Actual lethal hit produces impact, death and five-ADD readiness cues")
	await ticks(40)
	check(heard(&"add_collect"), "ADD collection cue aligns with the fragment reaching its meter")
	reset_cues()
	fighter.receive_damage(1)
	check(heard(&"hurt"), "Accepted player damage triggers the shared audible hurt cue")
	reset_cues()
	page.select_panel(1)
	check(heard(&"panel_switch"), "Actual panel selection triggers the switch cue")
	page.set_paused(true)
	check(heard(&"pause_open"), "Pause opens with its interface cue")
	reset_cues()
	var controls: Button = page.get_node("PauseOverlay/Center/Card/Margin/Menu/Tabs/Controls")
	controls.mouse_entered.emit()
	controls.pressed.emit()
	check(heard(&"ui_hover") and heard(&"ui_click"), "Existing interface buttons are automatically wired for hover and click")
	check(not sfx.play_cue(&"dash", fighter), "Paused combat cannot emit movement noise")
	page.addition = 4
	page.assign_panel_role(2, &"Present")
	check(heard(&"ui_error"), "Rejected frame shift emits an error cue")
	page.addition = 5
	page.assign_panel_role(2, &"Present")
	check(heard(&"frame_shift") and page.addition == 0, "Affordable role exchange emits confirmation only after spending")
	reset_cues()
	check(sfx.play_cue(&"ui_hover") and not sfx.play_cue(&"ui_hover"), "Rapid hover events are throttled")
	check(sfx.source_gain(page.panels[0].arena.player, &"footstep") == -18.0 and sfx.source_gain(page.panels[1].arena.player, &"footstep") == 0.0, "Inactive movement is attenuated while the active arena remains clear")
	check(sfx.source_gain(page.panels[0].arena.player, &"hurt") == 0.0, "Inactive player damage remains audible")
	page.set_paused(false)
	page.hud.display_add = 5.0
	check(page.hud.add_segment_fill(4) == 1.0 and page.hud.add_segment_fill(5) == 0.0, "Five ADD fills exactly one five-segment bank")
	page.hud.display_add = 10.0
	check(page.hud.add_segment_fill(9) == 1.0, "Ten ADD fills both banks for a two-position shift")
	page.hud.display_add = 0.0
	check(page.hud.add_segment_fill(0) == 0.0, "Spending ADD clears the displayed segments")
	for voice in sfx.voices:
		voice.stop()
		voice.stream = null
	await ticks(8)
	finish("SOUND DESIGN")
